version: '3.1'

services:
  #monitoring-service:
  #  build: .
  #  ports:
  #    - "8080:8080"

  prometheus:
    build: ./prometheus
    volumes:
      - ./prometheus/storage:/prometheus

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/storage:/var/lib/grafana